from django.core.management.base import BaseCommand
from django.contrib.auth.models import User
from complaints.models import Complaint, Ward, Verification
from django.conf import settings
import time

class Command(BaseCommand):
    help = 'Tests the email notification flow by creating and verifying a dummy complaint'

    def handle(self, *args, **options):
        self.stdout.write("🧪 Starting Email Flow Test...")

        # 1. Check Email Settings
        if not settings.EMAIL_HOST_USER or not settings.EMAIL_HOST_PASSWORD:
            self.stdout.write(self.style.WARNING("⚠️  EMAIL_HOST_USER or EMAIL_HOST_PASSWORD not set in .env. Email sending might fail."))
        
        if settings.EMAIL_OVERRIDE_ADDRESS:
            self.stdout.write(self.style.SUCCESS(f"ℹ️  Emails will be redirected to: {settings.EMAIL_OVERRIDE_ADDRESS}"))
        else:
            self.stdout.write(self.style.WARNING("⚠️  EMAIL_OVERRIDE_ADDRESS not set. Emails might go to real addresses!"))

        try:
            # 2. Setup Test Data
            # Create/Get Ward
            ward, _ = Ward.objects.get_or_create(
                name="TEST-A",
                defaults={
                    'full_name': "Test Ward A",
                    'officer_email': "ward.officer@example.com" # Should be overridden
                }
            )
            self.stdout.write(f"✅ Ward '{ward.name}' ready.")

            # Create/Get Reporter
            reporter, _ = User.objects.get_or_create(username="test_reporter", defaults={'email': 'reporter@example.com'})
            if not reporter.password: reporter.set_password('testpass'); reporter.save()
            
            # Create/Get Verifier
            verifier, _ = User.objects.get_or_create(username="test_verifier", defaults={'email': 'verifier@example.com'})
            if not verifier.password: verifier.set_password('testpass'); verifier.save()

            # 3. Create Complaint
            complaint = Complaint.objects.create(
                title="Test Complaint for Email Verification",
                description="This is a test complaint generated by the test_email_flow script to verify email delivery.",
                category=Complaint.Category.GARBAGE,
                ward=ward,
                reporter=reporter,
                latitude=19.0760,
                longitude=72.8777,
                location_address="Test Location, Mumbai",
                urgency_score=8,
                ai_verified_category=True
            )
            self.stdout.write(f"✅ Created Complaint #{complaint.id}: {complaint.title}")

            # 4. Trigger Verification (This sends the email)
            self.stdout.write("🔄 Verifying complaint to trigger email...")
            Verification.objects.create(complaint=complaint, user=verifier)
            
            self.stdout.write(self.style.SUCCESS("✅ Verification added! Check your console logs above for 'Email sent...' message."))
            self.stdout.write(self.style.SUCCESS(f"📬 Please check the inbox of: {settings.EMAIL_OVERRIDE_ADDRESS or ward.officer_email}"))

        except Exception as e:
            self.stdout.write(self.style.ERROR(f"❌ Test Failed: {e}"))
            import traceback
            traceback.print_exc()
