# Generated by Django 5.2.8 on 2025-12-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("VERIFIED", "Community Verified"),
                    ("ESCALATED", "Escalated to Official"),
                    ("RESOLVED", "Resolved"),
                    ("REOPENED", "Reopened"),
                ],
                default="NEW",
                max_length=20,
            ),
        ),
    ]
