# Generated by Django 5.2.8 on 2025-12-04 15:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0003_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="admin_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="complaint",
            name="user_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
