# Generated by Django 5.2.8 on 2025-12-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0004_complaint_admin_token_complaint_user_confirmed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="category",
            field=models.CharField(
                choices=[
                    ("POTHOLE", "Pothole"),
                    ("GARBAGE", "Garbage/Debris"),
                    ("DRAINAGE", "Drainage/Flooding"),
                    ("LIGHTING", "Street Lighting"),
                    ("WATER", "Water Supply"),
                    ("SANITATION", "Public Toilets/Sanitation"),
                    ("TRAFFIC", "Traffic/Parking"),
                    ("PARKS", "Parks/Gardens"),
                    ("OTHERS", "Others"),
                ],
                default="OTHERS",
                max_length=20,
            ),
        ),
    ]
