# Generated by Django 5.2.8 on 2025-12-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0005_alter_complaint_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="escalation_level",
            field=models.IntegerField(
                default=0, help_text="0=Ward, 1=Zone, 2=Commissioner"
            ),
        ),
    ]
